---
params:
  projectdir: !expr here::here() # "~/path/to/project" # Use  when loading. Can also hard code if for some reason you need that
  project_name: "Default"        # Change depending on your project name
  species: "rat"                 # one of human, mouse, rat, hamster
  design: "Group"                # single experimental group of interest; entries in this column must match the contrast names.
  intgroup: ["Group"]            # experimental group of interest plus covariates; can be more than one
  nuisance:  NA                  # "Batch" To remove batch effects for PCA/Heatmaps visualiziations
  flag: TRUE                     # runs all analysis by default when set to TRUE
  platform: "RNA-Seq"            # RNA-Seq or TempO-Seq
  group_facet: "Timepoint"       #!expr NA # If you have many different experimental groups, you may subset the report by specifying a column in the metadata to filter groups, and then setting the group of interest in group_filter
  group_filter:  "5D"            # !expr NA # Which group will this report be done on?
  strict_contrasts: TRUE         # Use both columns (exp, cont) of contrasts file to limit what is included in the report
  exclude_samples: !expr NA      # Optionally, a vector of sample names to exclude from the analysis
  exclude_groups: !expr NA       # Optionally, a vector of groups to exclude from the analysis. By default this is assumed to be in the column specified by params$design.
  include_only_column:  !expr NA # Restrict analysis to group(s) in the column listed here based on params$include_only_group.
  include_only_group:  !expr NA  # Restrict analysis to this/these group(s) within the column listed in params$include_only_column
  use_cached_RData: FALSE        # If possible, load the saved RData for dds object and gene IDs
  cpus: 41                       # Set to a lower number (e.g., 2 to 4) if you aren't working in a server environment
  run_pathway_analysis: TRUE     # Optionally disable pathway analysis if not available for your organism
  wikipathways_directory: "~/shared/dbs/wikipathways"
  biospyder_dbs: "~/shared/dbs/biospyder/"
  nBestFeatures: 20              # The number of best features to make plots of their counts
  nBest: 100                     # Number of features to include in table and limiting PCA/clustering analysis
  nHeatmap: 50                   # Number of most variable genes for heatmap
  nHeatmapDEGs: 50               # Number of DEGs for heatmap
  sampledata_sep: "\t"           # Comma for TempO-Seq, Maybe tabs for RNASeq, customize!
---
